version: "2.1"
orbs:
  toolkit: storytel/toolkit@1
workflows:
  ci:
    jobs:
      # Run on branches and PRs. Only tests, nothing is published
      - toolkit/jvm-gradle-ci:
          name: ci-pr-branch
          context: gcloud-storytel-build
          filters:
            branches:
              ignore: main
          docker_test_build: true
          sonarqube_pr: true
      # Runs on commits to the main branch. A snapshot docker image is pushed
      - toolkit/jvm-gradle-ci:
          name: ci-base-branch
          context: gcloud-storytel-build
          filters:
            branches:
              only: main
          docker_push_snapshot: true
          sonarqube_base: true
      # Runs when tags in the form "1.2.3" or "1.2.3-alpha" are created. A docker image is published using the tag
      - toolkit/jvm-gradle-ci:
          name: ci-release-tag
          context: gcloud-storytel-build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^[0-9]+\.[0-9]+\.[0-9]+(\-.*)?$/'
          skip_tests: true
          docker_push_git_tag: true
